---
- name: Retrieve VM id
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
      - "{{ vmware_name }}"
  register: new_vm_id

- name: show vm id
  debug:
    msg: "power: {{ new_vm_id }}"

- name: Retrieve VM id
  debug:
    msg: "power: {{ new_vm_id.value[0].power_state }}"

- name: Turn VM off
  vmware.vmware_rest.vcenter_vm_power:
    state: stop
    vm: "{{ new_vm_id.value[0].vm }}"
  when: 
    - new_vm_id.value[0].power_state is defined
    - new_vm_id.value[0].power_state == "POWERED_ON"

- name: Delete VM
  vmware.vmware_rest.vcenter_vm:
    state: absent
    vm: "{{ new_vm_id.value[0].vm }}"

